name: Build aarch64-linux-musl

on:
  push:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build project
        run: |
          sudo chmod +x build.sh
          ./build.sh

      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aarch64-linux-musl.tar.gz
          tag_name: ${{ steps.bump.outputs.new_tag }}

      - name: Sending logs to artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Process log
          path: |
            process.log
